name: Deploy HTML to WordPress

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # リポジトリをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3

      # jq をインストール（JSON 変換用）
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      # posts フォルダの内容を確認
      - name: List posts folder
        run: ls -la posts

      # WordPress に投稿
      - name: Deploy posts to WordPress
        env:
          WP_USER: ${{ secrets.WP_USER }}   # 管理者ユーザー名
          WP_PASS: ${{ secrets.WP_PASS }}   # アプリケーションパスワード
        run: |
          for file in posts/*.html; do
            TITLE=$(basename "$file" .html)
            # HTML を JSON に変換して temp.json に保存
            jq -Rs --arg title "$TITLE" '{title:$title, content:., status:"publish"}' < "$file" > temp.json

            # curl で WordPress に投稿
            curl -u "$WP_USER:$WP_PASS" \
                 -X POST "https://kabu24h365dojo.shop/wp-json/wp/v2/posts" \
                 -H "Content-Type: application/json" \
                 --data-binary @temp.json
          done
