name: Deploy HTML to WordPress

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted  # 自己ホストランナーを指定

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List posts folder
        run: ls -la posts

      - name: Deploy posts to WordPress
        run: |
          #!/bin/bash
          set -e

          for file in posts/*.html; do
            TITLE=$(basename "$file" .html)
            echo "=== 投稿中: $TITLE ==="

            # HTML を安全に JSON 文字列に変換して temp.json に保存
            jq -Rs --arg title "$TITLE" '{title:$title, content:., status:"publish"}' < "$file" > temp.json

            # curl で WordPress に投稿
            RESPONSE=$(curl -s -w "%{http_code}" -o response.json \
              -u "${{ secrets.WP_USER }}:${{ secrets.WP_PASS }}" \
              -X POST "https://kabu24h365dojo.shop/wp-json/wp/v2/posts" \
              -H "Content-Type: application/json" \
              --data-binary @temp.json)

            HTTP_STATUS="${RESPONSE:(-3)}"

            if [ "$HTTP_STATUS" -ge 200 ] && [ "$HTTP_STATUS" -lt 300 ]; then
              echo "投稿成功: $TITLE"
            else
              echo "投稿失敗: $TITLE"
              cat response.json
              exit 1
            fi
          done
